### ISSUE TITLE
虚拟机里尝试安装，出错

### ISSUE THREAD

**Issue by carlos444** [shi-yang/iisns#12]
安装环境virtualbox 5.1, CentOS 7.3 lnmp1.3
出错信息很简略，求解决方案。
![- 2017 01 31 - 23 36 03](https://cloud.githubusercontent.com/assets/2613235/22471803/686bedd2-e80e-11e6-84b1-c0aa2bca4216.png)

**Comment by shi-yang** [comment]
是这个安装程序写得不够好，我得改下，改好后我再关闭这个 issue，请问，数据库中有插入表了么

**Comment by carlos444** [comment]
装了几次，数据库都是插入了表的。
