### ISSUE TITLE
install网页版在电脑火狐浏览器排版错乱

### ISSUE THREAD

**Issue by bubifengyun** [shi-yang/iisns#2]
火狐浏览器41版，排版错乱的地方是footer.php位置不在最下部，遮挡了上面框框的输入。

另外超级管理员的名字如果不设为admin，写入数据库也会报错，说是10000重复输入，已经存在该ID。

**Comment by shi-yang** [comment]
谢谢！

**Comment by shi-yang** [comment]
第二个问题应该是无关 admin，可能是已经插入过这么一条数据，数据库已经存在了个账号。不管超级管理员名字是什么，它的ID默认都是 10000
