### ISSUE TITLE
安装界面建议

### ISSUE THREAD

**Issue by bubifengyun** [shi-yang/iisns#3]
那个install界面分为三步，我感觉没有太大必要，不如直接一个网页来的好。

我感觉安装网页这么设计比较好。如果已经安装，显示安装完成的界面。如果没有安装，直接显示第二步需要填写的表格，下面来一个安装按钮就可以了。安装成功或失败，再跳转到一个页面。

说的可能不对，见谅。

**Comment by shi-yang** [comment]
嗯，这个install确实需要改进，比如安装成功了进度条显示不正确。第一步只是用来做个“欢迎使用”的问候，删倒不必，但还应该在这下面加个环境需求检测的功能，检测文件是否可读写，是否满足安装yii2的环境需求等，如果考虑要国际化的，还得语言选择。
安装三步走，三是个很好的数字，多了会显繁琐，少了功能有限。
感谢提出！

**Comment by bubifengyun** [comment]
好的，谢谢啊。我慢慢改。
