### ISSUE TITLE
前端界面建议

### ISSUE THREAD

**Issue by bubifengyun** [shi-yang/iisns#4]
我感觉前端界面左端菜单栏的折叠不够明显。

摸索了一下，才知道要点击页面上方的那个三横杠的按钮可以实现折叠。
总感觉设计的比较丑陋。

可否在左端菜单栏跟右边主要页面的分界线上做个按钮。
一个大于号或小于号的按钮。点击他放宽或者缩窄左端菜单栏。

可能说的不对，见谅。

**Comment by shi-yang** [comment]
你提的这个需求，其实跟用了bootstrap这个前台框架有关，它框架是这样，由于我个人精力有限，所以我也没在这做过多纠结。

在页面的设计上，我只在尽自己的努力来一点点地完善每个页面。就我的观察而言，在个人中心的某个点上会有不协调的现象，但是我并不是专业设计师，在这方面尚欠缺天赋，我无法指出是哪里不对，但就是感觉不够好。
我也期待能有更多人来帮助完善它。

感谢提出！

**Comment by bubifengyun** [comment]
谢谢啊。如果我解决了，告诉你。
