### ISSUE TITLE
上传图片出错误 

### ISSUE THREAD

**Issue by suwenkkk** [shi-yang/iisns#6]
yii2-webuploader 上传图片 return server 错误 ！

**Comment by shi-yang** [comment]
嗯，注意到了，www.iisns.com上有这个问题，但是iisns源码中不存在这个问题。主要是因为网站上使用了七牛云储存，我更新服务器上的代码时把那些相关的文件给覆盖掉了~

**Comment by suwenkkk** [comment]
linux系统会有这个问题，window下没有
1。是上传文件权限的问题 chmod www -R 777 path 
2. 取上传文件的扩展名的问题 
    /**
     * 获取文件扩展名
     * @return string
     */
    private function getFileExt()
    {
        return  '.' . substr( strrchr( $this->file[ "type" ] , '/' ) ,1  );
    }

**Comment by shi-yang** [comment]
好吧，看来我误会你的意思了。不过我也是在linux下开发，因为没见有报错，所以也就没能发现。权限的话我已经在 install 安装器下增加了这个目录，提示用户给它增加权限。
我想请教下下，你写的这个获取文件扩展名函数与原来的这个
   /**
     * 获取文件扩展名
     * @return string
     */
    private function getFileExt()
    {
        return strtolower( strrchr( $this->file[ "name" ] , '.' ) );
    }
它的差别在哪呢？或者说什么情况下会导致原来这个报错，还是说原来这个有其它的不足之处？

**Comment by suwenkkk** [comment]
sorry ! /**
* 获取文件扩展名
* @return string
*/
private function getFileExt()
{
return strtolower( strrchr( $this->file[ "name" ] , '.' ) );
}
这个方法是正确的!
