### ISSUE TITLE
发现一个bug啊 

### ISSUE THREAD

**Issue by zxx1988328** [shi-yang/iisns#7]
就是注册了之后,发了一个说说,然后转发的时候报错了
![bug](https://cloud.githubusercontent.com/assets/6026852/13452570/e992e4e4-e083-11e5-9339-8f192db85312.png)

**好吧 ,其实是网速慢的原因**,不知道为什么,改了一些代码才可以运行,经常报错:比如知道没有默认值之类,还有注册的验证码就是怎么都不显示,gd2也开启了,就是不显示,到现在也没显示.
![Uploading 0000.png…]()
![Uploading 0000.png…]()

**Comment by zxx1988328** [comment]
上图片  
![0000](https://cloud.githubusercontent.com/assets/6026852/13452838/8ec6b4ac-e086-11e5-821c-5d89745241a3.png)
![Uploading 0000.png…]()

**Comment by shi-yang** [comment]
这个注册码的问题我也注意到了，在某些环境下出现不了，我也还没能找出原因。转发功能还有诸多不完善，bug还是挺多的。所以现在发布的版本都是提前预览版，并不是正式版本。

**Comment by zxx1988328** [comment]
@shi-yang  好的 谢谢回复 期待正式版哦

**Comment by Jchestnut** [comment]
@zxx1988328  @shi-yang 图片不显示的问题是因为在验证码输出之前缓冲区存在内容了，在输出验证码前清空缓冲区就好。具体查看验证码生成那里的代码，感觉还不错，期待正正式版！

**Comment by shi-yang** [comment]
@Jchestnut 嗯，清空了确实可以。

**Comment by shi-yang** [comment]
@Jchestnut 不过，你知道怎么才会出现这种情况吗？同样一台电脑，要是下载官方的那个基础版本，看联系那个页面的验证码的话，也可以显示出来

**Comment by shi-yang** [comment]
哎，不小心关闭了。我问官方的人，他问能不能复现一下这个 bug，可是在有些机子上它又不出现

**Comment by Jchestnut** [comment]
@shi-yang 鉴于这个问题我对缓冲区进行了追踪，最终定位到了**common目录下的db.php文件**加载时产生，而后发现了该文件第一行为空，也就是说换行了，由于php的require的加载机制缓冲区里面存在了换行符，**把给文件第一行删掉就行了**。为什么有一些人可以用？估计是有些人并不是通过install目录下的index安装的，细心看一下**install目录下的index文件可以发现在创建db.php文件时输入的时候**换行导致的，作者看一下这里的代码，**不换行即可**。

**Comment by shi-yang** [comment]
@Jchestnut  可以了，谢谢啊！！！我还有好多东西要学啊。。
